### ISSUE TITLE
Server Sided History

### ISSUE THREAD

**Issue by Catscratch** [jitsi/jitsi#360] opened 2017-05-11 07:48 UTC
Is there a way to use server sided chat history for XMPP? We're using  OpenFire 4.1.2 as XMPP server which supports this feature.

Thanks!

**Comment by ibauersachs** [comment] 2017-07-02 10:44
This would be XEP-0313 - Message Archive Management.

Closing as duplicate of #205.

**Closed by ibauersachs** 2017-07-02 10:44 UTC
