### ISSUE TITLE
Nested groups (Openfire)

### ISSUE THREAD

**Issue by jakobeissler** [jitsi/jitsi#331] opened 2017-02-23 16:54 UTC
Hello,

We use Openfire as a XMPP chat server and have configured virtual nested groups like this:

```
- Enterprise 1
          - Area 1
          - Area 2
          - ...
          - Area n
- Enterprise 2
          - Area 1
          - Area 2
          - ...
          - Area n
```

In Openfire those groups are set like this: 

`Enterprise 1 :: Area 1`

Is there any chance Jitsi could show this nested groups?

**Comment by ibauersachs** [comment] 2017-02-23 17:56
Duplicate of #88

**Closed by ibauersachs** 2017-02-23 17:56 UTC

**Comment by jakobeissler** [comment] 2017-02-23 18:01
I'm sorry i think i didn't explain the problem quiet well. I edited the issue.

**Comment by ibauersachs** [comment] 2017-02-23 18:42
If anything would be changed how groups are handled, then this would be as part of #88. The contact list is one of the more complex things in Jitsi and would require a lot of work. Unless someone from the community comes along with a pull request, there's unfortunately nothing going to happen anytime soon.

**Comment by jakobeissler** [comment] 2017-02-23 18:49
I understand. Thank You.
