### ISSUE TITLE
Can't connect jitsi to google contacts.

### ISSUE THREAD

**Issue by djhaskin987** [jitsi/jitsi#326] opened 2017-02-17 20:00 UTC
Starting from a mac machine, running Jitsi 2.10.5550, I removed and added my google talk account using an app password. Then the dialog box shows up asking me to click on the link and get the auth token from google so that Jitsi can use my google contacts. Except it doesn't work. a stack trace is printed in the logs and the dialog box just pops back up:

```
2017-02-17 12:50:22.723 INFO: [16036] impl.googlecontacts.OAuth2TokenStore.acquireCredential().195 No credentials available yet. Requesting user to approve access to Contacts API for identity <REDACTED>@gmail.com using URL: https://accounts.google.com/o/oauth2/auth?scope=profile%20email%20https://www.google.com/m8/feeds&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&client_id=262996337167-s0euqlton0s8g3tsar93ck4jlugqgqb1.apps.googleusercontent.com
2017-02-17 12:50:26.066 SEVERE: [16036] impl.googlecontacts.GoogleContactsConnectionImpl.connect().127 Failed to acquire credentials.
net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore$FailedAcquireCredentialException: java.lang.NullPointerException
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.get(OAuth2TokenStore.java:169)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsConnectionImpl.connect(GoogleContactsConnectionImpl.java:122)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsSourceService.getConnection(GoogleContactsSourceService.java:261)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsQuery.run(GoogleContactsQuery.java:129)
	at net.java.sip.communicator.service.contactsource.AsyncContactQuery$1.run(AsyncContactQuery.java:325)
Caused by: java.lang.NullPointerException
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore$TokenData.access$500(OAuth2TokenStore.java:559)
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.createCredential(OAuth2TokenStore.java:359)
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.acquireCredential(OAuth2TokenStore.java:228)
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.get(OAuth2TokenStore.java:165)
	... 4 more
2017-02-17 12:50:26.208 INFO: [16036] impl.googlecontacts.GoogleContactsConnectionImpl.query().160 Executing query failed with NPE. Refreshing access token and trying again.
2017-02-17 12:50:26.208 WARNING: [16036] impl.googlecontacts.GoogleContactsServiceImpl.searchContact().277 Problem occurred during Google Contacts query
java.lang.IllegalStateException: A credential instance should exist, but it does not. This is likely due to a bug.
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.refresh(OAuth2TokenStore.java:274)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsConnectionImpl.query(GoogleContactsConnectionImpl.java:164)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsServiceImpl.searchContact(GoogleContactsServiceImpl.java:273)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsQuery.run(GoogleContactsQuery.java:136)
	at net.java.sip.communicator.service.contactsource.AsyncContactQuery$1.run(AsyncContactQuery.java:325)
2017-02-17 12:50:49.705 INFO: [484] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().125 Jingle : OFF 
2017-02-17 12:53:02.567 INFO: [16072] impl.googlecontacts.OAuth2TokenStore.acquireCredential().195 No credentials available yet. Requesting user to approve access to Contacts API for identity <REDACTED>@gmail.com using URL: https://accounts.google.com/o/oauth2/auth?scope=profile%20email%20https://www.google.com/m8/feeds&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&client_id=262996337167-s0euqlton0s8g3tsar93ck4jlugqgqb1.apps.googleusercontent.com
2017-02-17 12:53:02.932 INFO: [16061] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin().1290 Chosen TLS protocol and algorithm:
Protocol: TLSv1.2
Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
2017-02-17 12:53:02.933 INFO: [16061] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().118 Jingle : ON 
2017-02-17 12:53:03.670 WARNING: [16079] impl.protocol.jabber.OperationSetBasicInstantMessagingJabberImpl.isCarbonSupported().775 Failed to retrieve carbon support.remote-server-not-found(404)
2017-02-17 12:53:04.007 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact asachild@myldsmail.net : service-unavailable(503)
2017-02-17 12:53:04.196 SEVERE: [16086] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact 1o843hdmqld0u@id.talk.google.com : service-unavailable(503)
2017-02-17 12:53:04.208 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact 1o843hdmqld0u@id.talk.google.com : service-unavailable(503)
2017-02-17 12:53:04.646 INFO: [16090] impl.protocol.jabber.JingleNodesServiceDiscovery.run().106 Start Jingle Nodes discovery!
2017-02-17 12:53:04.886 INFO: [16090] impl.protocol.jabber.JingleNodesServiceDiscovery.run().139 Jingle Nodes discovery terminated! 
2017-02-17 12:53:04.886 INFO: [16090] impl.protocol.jabber.JingleNodesServiceDiscovery.run().140 Found 0 Jingle Nodes relay for account: djhaskin987@gmail.com in 240 ms.
2017-02-17 12:53:07.539 INFO: [484] impl.googlecontacts.OAuth2TokenStore.actionPerformed().496 Requesting user for approval via web page: https://accounts.google.com/o/oauth2/auth?scope=profile%20email%20https://www.google.com/m8/feeds&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&client_id=262996337167-s0euqlton0s8g3tsar93ck4jlugqgqb1.apps.googleusercontent.com
2017-02-17 12:53:09.209 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact dblack@devry.com : No response from server.
2017-02-17 12:53:09.745 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact 0ncicrb5s3rh6@id.talk.google.com : service-unavailable(503)
2017-02-17 12:53:12.081 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact lane.broadbent@gmail.com : service-unavailable(503)
2017-02-17 12:53:12.230 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact lb425@gmail.com : service-unavailable(503)
2017-02-17 12:53:13.423 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact nmhuntsman@gmail.com : service-unavailable(503)
2017-02-17 12:53:14.687 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact taylorjoannjohnson@gmail.com : service-unavailable(503)
2017-02-17 12:53:14.785 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact atona@hotmail.com : remote-server-not-found(404)
2017-02-17 12:53:14.883 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact bettehaskin@hotmail.com : remote-server-not-found(404)
2017-02-17 12:53:14.977 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact care_bear_sar@hotmail.com : remote-server-not-found(404)
2017-02-17 12:53:15.074 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact jatoney@hotmail.com : remote-server-not-found(404)
2017-02-17 12:53:15.317 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact michellehaskin@hotmail.com : remote-server-not-found(404)
2017-02-17 12:53:15.413 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact sing4life88@hotmail.com : remote-server-not-found(404)
2017-02-17 12:53:15.507 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact marie_dramaqueen@yahoo.com : remote-server-not-found(404)
2017-02-17 12:53:15.603 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact jenc89@msn.com : remote-server-not-found(404)
2017-02-17 12:53:17.943 SEVERE: [16084] impl.protocol.jabber.InfoRetreiver.retrieveDetails().361 Cannot load details for contact 2ymtaxu4gtguw3p772ckwl6yfz@public.talk.google.com : service-unavailable(503)
2017-02-17 12:53:18.705 SEVERE: [16072] impl.googlecontacts.GoogleContactsConnectionImpl.connect().127 Failed to acquire credentials.
net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore$FailedAcquireCredentialException: java.lang.IllegalArgumentException: no JSON input found
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.get(OAuth2TokenStore.java:169)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsConnectionImpl.connect(GoogleContactsConnectionImpl.java:122)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsSourceService.getConnection(GoogleContactsSourceService.java:229)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsQuery.run(GoogleContactsQuery.java:129)
	at net.java.sip.communicator.service.contactsource.AsyncContactQuery$1.run(AsyncContactQuery.java:325)
Caused by: java.lang.IllegalArgumentException: no JSON input found
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:49)
	at com.google.api.client.json.JsonParser.startParsing(JsonParser.java:222)
	at com.google.api.client.json.JsonParser.startParsingObjectOrArray(JsonParser.java:239)
	at com.google.api.client.json.JsonParser.skipToKey(JsonParser.java:202)
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.requestAuthenticationToken(OAuth2TokenStore.java:402)
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.acquireCredential(OAuth2TokenStore.java:212)
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.get(OAuth2TokenStore.java:165)
	... 4 more
2017-02-17 12:53:18.828 INFO: [16072] impl.googlecontacts.GoogleContactsConnectionImpl.query().160 Executing query failed with NPE. Refreshing access token and trying again.
2017-02-17 12:53:18.828 WARNING: [16072] impl.googlecontacts.GoogleContactsServiceImpl.searchContact().277 Problem occurred during Google Contacts query
java.lang.IllegalStateException: A credential instance should exist, but it does not. This is likely due to a bug.
	at net.java.sip.communicator.impl.googlecontacts.OAuth2TokenStore.refresh(OAuth2TokenStore.java:274)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsConnectionImpl.query(GoogleContactsConnectionImpl.java:164)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsServiceImpl.searchContact(GoogleContactsServiceImpl.java:273)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsQuery.run(GoogleContactsQuery.java:136)
	at net.java.sip.communicator.service.contactsource.AsyncContactQuery$1.run(AsyncContactQuery.java:325)
interrupt: 2
```

Sad day :(

**Comment by ibauersachs** [comment] 2017-02-17 22:28
Duplicate of #323

**Closed by ibauersachs** 2017-02-17 22:28 UTC
