### ISSUE TITLE
Registration Expiry Duration change on SIP server not affecting Jitsi.

### ISSUE THREAD

**Issue by EngHooda** [jitsi/jitsi#349] opened 2017-04-03 21:36 UTC
Hello,
I have a kamailio SIP server and I use Jitsi as my preferred client as it has more features than other SIP clients .
In windows 64bit version I noticed that changing max_expires parameter on the SIP server to lower than the default of 1 Hour does not trigger the expected more frequent registration from Jitsi.
I used the following kamailio.cfg line to lower registration expiration to 6min instead of 60min , to have more accurate view of online users.
modparam("registrar", "max_expires", 360)
having Jitsi running on my PC for hours , I noticed that my user is repeatedly going offline.
I use the following command to check online users.
kamctl ul show --brief

I hope this issue could be fixed
Thanks & Best Regards,
Eng Hooda

**Comment by ibauersachs** [comment] 2017-04-06 08:57
Duplicate of #339

**Closed** 2017-04-06 08:57 UTC
