### ISSUE TITLE
Tray icon is not responding on any actions in gnome shell

### ISSUE THREAD

**Issue by corpix** [jitsi/jitsi#257] opened 2016-05-08 21:23 UTC
I am using a Fedora 23 with Gnome Shell.
Jitsi tray icon is not responding to any actions so when I am close the Jitsi there is no way to bring it up again because the only way to do this(in other systems) is to double click on the tray icon.

P. S. Personaly I'll be comfortable with the option allows me to completely disable the tray icon(tray is useless and ugly under gnome shell).

**Comment by ibauersachs** [comment] 2016-05-09 04:32
Duplicate of #192

**Closed by ibauersachs** 2016-05-09 04:32 UTC
