### ISSUE TITLE
Contacts in multiple XMPP groups

### ISSUE THREAD

**Issue by lmbss** [jitsi/jitsi#316] opened 2017-02-09 08:18 UTC
When in XMPP a contact is present in several groups in jitsi so it appears in the first group.
Example:

My server loads the contacts in the XMPP client, so if contact1 belongs to group1 and group2 in jitsi is only visible in group1, in group2 contact1 no longer appears

**Comment by ibauersachs** [comment] 2017-02-09 08:34
Duplicate of #88

**Closed by ibauersachs** 2017-02-09 08:34 UTC

**Comment by GNUDimarik** [comment] 2018-09-20 13:10
@lmbss can you help me with testing?
Here is the build: https://www.dropbox.com/s/lyjb40jtynzmjzx/setup.msi?dl=0
Sorry for big package. But please try it if you can.
Please share the logs and scenario if you have some issues.
