### ISSUE TITLE
Jitsi jitsi-2.10.5550 hangs on splashscreen during startup

### ISSUE THREAD

**Issue by EUFC19** [jitsi/jitsi#328] opened 2017-02-21 07:40 UTC
tried updating jitsi software and jitsi crashed

installed using new installer ... same

![image](https://cloud.githubusercontent.com/assets/25921738/23155076/f5718bcc-f84b-11e6-9df9-da446cd034aa.png)

Stuck in a loop

**Comment by EUFC19** [comment] 2017-02-21 07:41
tried delete %appdata%, reinstall, same issue faced

**Comment by ibauersachs** [comment] 2017-02-23 17:57
Duplicate of #321

**Closed by ibauersachs** 2017-02-23 17:57 UTC
