### ISSUE TITLE
Transfer file png / jpg do not work.

### ISSUE THREAD

**Issue by zimasanya** [jitsi/jitsi#510] opened 2018-07-28 10:30 UTC
Hi,

The trasnfert file bmp, doc, zip etc is ok
for the png and jpg : ko (nothing is happening)

if i rename the jpg file to bmp or whatever it works

I do not understand where it can come from because with another client on the same server it works.
Win / mac / linux Version stable : 2.10.5550 and nightly build too

**Comment by GNUDimarik** [comment] 2019-05-29 22:00
It seems duplicate of this issue: https://github.com/jitsi/jitsi/issues/435. Fix already exists but some additional work needs to be done.
@ibauersachs can we close this?

**Comment by GNUDimarik** [comment] 2019-08-21 12:30
@ibauersachs @damencho this issue is duplicate of fixed issue. Please close once you have time on it

**Closed** 2019-08-21 12:45 UTC
