### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by chenshixiu** [jitsi/jitsi#346] opened 2017-03-23 09:41 UTC
I system with Windows 7, jdk7, jre7
Login error: user name: anna# shenzhen jie @ 114.119.7.210 dimension information technology co., LTD, the server name: Jabber.
Login unsuccessful!!!

2017-03-23 09:48:11.888 严重: [961] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectUsingSRVRecords().912 No SRV addresses found for _xmpp-client._tcp.114.119.7.210
2017-03-23 09:48:12.768 严重: [961] util.account.LoginManager.run().442 Failed to register protocol provider. 
java.lang.ArrayIndexOutOfBoundsException: 0
How to solve this problem?

**Comment by ibauersachs** [comment] 2017-03-23 10:30
Duplicate of #345.

Please ask for help on the mailing list. The issue tracker is meant for issues, not for support questions.

**Closed by ibauersachs** 2017-03-23 10:30 UTC
