### ISSUE TITLE
Jitsi client ignores server set SIP contact expiry

### ISSUE THREAD

**Issue by davemidd** [jitsi/jitsi#339] opened 2017-03-15 13:56 UTC
I'm using Jitsi for Windows 2.10.5550.  The client requests a contact expiry of 600 seconds (in the SIP Contact header). The Registrar returns an expiry of 90 seconds (in the SIP Contact header). Jitsi appears to ignore this value and just re-registers as if the contact expiry was as originally requested (i.e. after every 540 seconds).  This causes the client to become un-registered for long periods of time and so does not receive calls. I've seen this issue on a number of different Windows installs.  (I'm using 'Keep alive method = none' as I want to honour the server set expiry.)

It was mentioned on the Users list back in 2015 (http://lists.jitsi.org/pipermail/users/2015-November/010509.html) but I've seen no further mention of the problem.  I posted to the list a day ago (http://lists.jitsi.org/pipermail/users/2017-March/012519.html).

Many thanks.

**Comment by davemidd** [comment] 2017-03-27 11:08
Hi guys. Do you need any more info from me?
Thanks.

**Comment by cobratbq** [comment] 2017-04-08 18:42
@ibauersachs @damencho Can anyone of you guys judge if this may be the problem?
https://github.com/jitsi/jitsi/tree/fix-sip-contact-expiry-header

**Comment by ibauersachs** [comment] 2017-04-09 13:02
@cobratbq looks good enough for me to merge. The bug reporters can then check with the nightly.

Thanks for looking at it!

**Comment by davemidd** [comment] 2017-04-10 14:45
Hi.  I've installed the most recent nightly (jitsi-2.11.5565-x64 - 8th April) and unfortunately am still seeing the issue.  I assume that this commit got into that build?
Please let me know if there's anything else I can do to test or any other information I can provide.

**Comment by cobratbq** [comment] 2017-04-10 15:21
Hi David. I don't think it is merged yet. I haven't had time to do it yet.
I'll post an update once I do, so you can check once you're sure that the
fix is in.

**Comment by damencho** [comment] 2017-04-10 15:23
I merged an hour ago, but there are problem with builds conflicts in GoogleAPIClientToken, I'm fixing them now and how to have build in few hours.

**Comment by jitsi-developers** [comment] 2017-04-10 16:00
Huh, ... I'm surprised. Is it caused by this commit? Did I screw something
up there? Otherwise I'm willing to take a quick look later tonight. Just
give me some details if you need me to. The change here is just a single
file.

**Comment by damencho** [comment] 2017-04-10 16:05
Don't worry. I think I've fixed it, it's that during build we are modifying this file, and it had conflicts while building the macosx builds...

**Comment by damencho** [comment] 2017-04-10 17:07
Hey @davemidd build 5566 is out, can you test it? Thanks.

**Comment by davemidd** [comment] 2017-04-10 18:30
Hi @damencho 
Good news! Jitsi2.11.5566Windows 1 is all working for me now.
Jitsi is correctly re-registering based on the server set contact expiry.

I ran a number of tests with different server expiry times - see [register-times.txt](https://github.com/jitsi/jitsi/files/911039/register-times.txt).

I think there is one slight bug;  when the expiry > 60s, then Jitsi re-registers at 0.9 x expiry.  However, when the expiry is <= 60s, Jitsi re-registers at the exact expiry time (actually some mS after the expiry due to propagation delays) and so potentially would not be registered for a very brief interval.  It could also add unnecessary load on the registrar as it would be removing the contact and re-adding a new contact on each register.

(Please note that I've only tested with 'Keep alive method' set to 'NONE'.)

Many thanks.

**Comment by damencho** [comment] 2017-04-10 18:55
Cool, thanks for testing this.

**Closed by damencho** 2017-04-10 18:55 UTC

**Comment by damencho** [comment] 2017-04-10 18:57
And thanks @cobratbq for fixing it :)

**Comment by davemidd** [comment] 2017-04-10 22:09
Thanks. I just wanted to check what the process is for getting the fix into a release version? Please excuse my lack of knowledge!

I also just wanted to ask if I should raise a separate issue over the re-register strategy when the server contact expiry response >= 60s, as I mentioned above?

**Comment by damencho** [comment] 2017-04-10 22:18
We do not backport fixes, fixes go in new releases. So for this fix, at the moment you can only use latest nightly.
Yep, open a new issue, thanks.

**Comment by damencho** [comment] 2017-04-10 22:23
It is strange:
https://github.com/jitsi/jitsi/blob/5f9610cbb2d2ed89afe033b4691d607d408393a6/src/net/java/sip/communicator/impl/protocol/sip/SipRegistrarConnection.java#L793-L793

I wonder is there a reason to handle that only for expires more than 60 seconds and not for all values.

**Comment by davemidd** [comment] 2017-04-10 22:33
That is odd. I can't think of any reason why you wouldn't want to schedule a re-register always before the expiry.

**Comment by cobratbq** [comment] 2017-04-10 22:36
Wow, that was a very quick fix. You made my day ... I didn't expect this to be so easy :-D

"everything over 60 secs" is an awfully specific way of working ... it's also confirmed by @davemidd . I don't know SIP at all, so I don't have a clue on whether this is desired behavior. It seems kinda arbitrary.

It would be nice if we can open a new issue and also reference @damencho code link in there, as well as the timings file. I see @davemidd point where, if you're slightly later with your reregistration, you've just given the server a few milliseconds to unregister the "expired client" from the system.

**Comment by damencho** [comment] 2017-04-11 02:08
Pushed a fix and it will be available in build 5567.

**Comment by davemidd** [comment] 2017-04-11 10:44
Thanks @damencho 
Build 5567 looks good. Sub-60s expiries are now being refreshed at time-10%.
