### ISSUE TITLE
Call button hidden, when contact uses multiple clients

### ISSUE THREAD

**Issue by 459below** [jitsi/jitsi#147] opened 2015-08-26 15:57 UTC
Sometimes the call button just gets hidden/greyed out by jitsi (desktop) even though the contact is running jitsi (android). It seems it is directly related to whether the contact is running another client. Imagine the following:

Alice has Bob in her list.
Bob starts Jitsi-Android on his phone.
Alice gets call button next to Bob in contact list.
Bob starts other non-jingle client (i.e. ChatSecure)
Alice cannot call Bob anymore, since call button gets hidden/greyed out. Even though both are running Jitsi at this point.

I'm familiar with the Jingle protocol, but I would assume that it supports multiple resources. JitsiAndroid does something similar BTW. This happens even if JitisAndroid has higher priority than the other clients. It seems to crucial to start Jitsi after all other clients.

**Comment by ibauersachs** [comment] 2015-08-26 21:27
Duplicate of #111

**Closed by ibauersachs** 2015-08-26 21:27 UTC
