### ISSUE TITLE
Jitsi in macOS High Sierra using high-performance graphics card

### ISSUE THREAD

**Issue by thewinger** [jitsi/jitsi#408] opened 2017-10-10 07:57 UTC
Jitsi activates high-performance graphics card in macOS High Sierra 10.13 Beta (17A362a)

<img width="972" alt="screen shot 2017-10-10 at 09 54 35" src="https://user-images.githubusercontent.com/121455/31375318-6696ab60-ada1-11e7-9d89-52d3cb31d8ef.png">

**Comment by ibauersachs** [comment] 2017-10-10 08:00
Duplicate of #119

**Closed by ibauersachs** 2017-10-10 08:00 UTC
