### ISSUE TITLE
Wrong timestamp in RTP when using AMR-WB 

### ISSUE THREAD

**Issue by napcode** [jitsi/jitsi#613] opened 2019-09-20 15:13 UTC
We've been using Jitsi for some time with G711 and other codecs. We just tried using AMR-WB but ran into issues. Apparently, Jitsi is sending decreasing RTP timestamps in this configuration. A corresponding PCAP is attached (first few packets of the call including SIP). Rendering of the incoming stream did not work either. Are there any helpful logs for that? PCAP looks okay in this direction.  

Please let me know if more information is needed.
[amr-wb.zip](https://github.com/jitsi/jitsi/files/3636559/amr-wb.zip)

**Comment by traud** [comment] 2019-11-28 17:19
I am not a team member but an external contributor. Anyway, I am able to confirm your finding with Jitsi Desktop 2.10 and the current nightly of 2.11. The issue is within LibJitsi. Until my change is merged, you have to build LibJitsi and Jitsi Desktop[ yourself…](https://community.jitsi.org/t/18436)

> rendering of the incoming stream did not work

My change just fixes Jitsi as **sender**. That fixed all my issues. Therefore, what means ‘incoming’ in this context: Is your Jitsi Desktop not able to play AMR-WB as **receiver** as well? In that case, which app do you use on the other side?

**Comment by napcode** [comment] 2019-11-28 20:49
Thanks for looking into it! Sorry I forgot to update this report. We've found an issue on our end as well. It most likely caused the rendering issue I was referring to. I'll try to test both directions using the patch as soon as I can.

**Comment by traud** [comment] 2019-12-02 15:58
Yes, please, test as soon as possible because I am not a constant contributor to this project and might be off in a few days again. By the way, just out of curiosity: Why don’t you use G.722 instead of AMR-WB?

**Closed** 2019-12-09 22:55 UTC
